### PR TITLE
Change the toon's name from "The Inspector" to Flippy.

### PR DESCRIPTION
**Pull request by TTPeppermint2011**

### CODE REVIEW

**Comment by Puggyblue999** [comment]
Idk, "The Inspector" sounds more literal

**Comment by TTPeppermint2011** [comment]
Flippy sounds better(in my opinion).

**Comment by Sparkpin** [comment]
This shouldn't be pulled until the nametag actually works

**Comment by TTPeppermint2011** [comment]
Okay, thanks for the feedback @Sparkpin .

**Comment by JawhnL5** [comment]
@Puggyblue999 
If we had the DNA string and knew what Disney's "Inspector" actually looked like, we'd leave it stock, but since it's Flippy (which is the next best thing), it makes sense to rename it to Flippy.

**Comment by Puggyblue999** [comment]
Yeah, I noticed after inspecting a little more that the DNA string looked like Flippy.

**Pull request merged**
