### PR TITLE
more baseline styles

### PR DESCRIPTION
**Pull request by encryptable**
These are based off of assumption..

I can also push the .dlls if you'd like.

### CODE REVIEW

**Comment by JawhnL5** [comment]
What .dlls are you talking about?

**Comment by encryptable** [comment]
@JawhnL5 The ones you need to run it.. or at least for me and most likely everyone else trying to run this.

**Comment by JawhnL5** [comment]
libotp, libtoontown and everything else are included in this repo. All you have to do is download it, add in the Toontown phase files and run the batch file to start it.

**Comment by encryptable** [comment]
@JawhnL5 I needed msvcr71.dll

**Comment by JawhnL5** [comment]
msvcr71.dll is in the "bin" folder it looks like.

**Pull request merged**
