### PR TITLE
LevelEditor Modifications and Additions - Sean

### PR DESCRIPTION
**Pull request by sean5470**
See the README_Sean.md for all the tweaks made.

### CODE REVIEW

**Comment by JawhnL5** [comment]
:+1: Looks good. Thanks Sean!

**Comment by sean5470** [comment]
LOL  that rar file had the new HQ storage dna's and the HQ dna's in it  :P

**Comment by JawhnL5** [comment]
Should I have left it? It's still on my local PC.

**Comment by sean5470** [comment]
up to you, but that is why I included it.  I created the dna storages and actual dna so users can load up all the HQ's

**Pull request merged**
